### PR TITLE
[Feat] Add Android 13 push permission prompting

### PR DESCRIPTION
**Pull request by nan-li**
# Description
## One Line Summary
This PR implements push permission prompting in Android for Android 13 devices.

### Motivation
This is a new Android 13 features/requirement.

### Scope
Push permission prompting on Android 13 devices. In order to not immediately be prompted in Android 13, apps will need to set their Android target SDK version to 33+.

There is a public API addition to give users more control. The public method `promptForPushNotificationsWithUserResponse(handler?)` now includes the optional boolean parameter `fallbackToSettings`. Omitting it maintains the same current behavior of not fallback to settings.

```typescript
promptForPushNotificationsWithUserResponse(fallbackToSettings?: boolean, handler?: (response: boolean) => void)
```

# Testing

## Manual testing
I tested on physical iPhone 13 and Android emulator on API 33 using combinations of allowing, denying, changing the permission in settings, and re-prompting. These are the ways of calling the method tested.

```typescript
OneSignal.promptForPushNotificationsWithUserResponse();

OneSignal.promptForPushNotificationsWithUserResponse(true);

OneSignal.promptForPushNotificationsWithUserResponse(false);

OneSignal.promptForPushNotificationsWithUserResponse(res => console.log(res));

OneSignal.promptForPushNotificationsWithUserResponse(undefined, (res) => console.log(res));

OneSignal.promptForPushNotificationsWithUserResponse(true, (res) => console.log(res));
```

There is some potentially undesirable behavior if a user taps outside the fallback to settings prompt to dismiss it. Since the SDK seems to be waiting on user interaction, the Android plugin's (and the user's) callback is not triggered until some definitive response is taken. Then they are all triggered. Included a short video to demonstrate.

https://user-images.githubusercontent.com/4022291/180971150-87ffc75d-4b2e-442a-a472-820a43b4e9dc.mov

# Affected code checklist
   - [x] Notifications
      - [ ] Display
      - [ ] Open
      - [ ] Push Processing
      - [ ] Confirm Deliveries
   - [ ] Outcomes
   - [ ] Sessions
   - [ ] In-App Messaging
   - [ ] REST API requests
   - [x] Public API changes

# Checklist
## Overview
   - [x] I have filled out all **REQUIRED** sections above
   - [x] PR does one thing
   - [x] Any Public API changes are explained in the PR details and conform to existing APIs

## Testing
   - [ ] I have included test coverage for these changes, or explained why they are not needed
   - [ ] All automated tests pass, or I explained why that is not possible
   - [x] I have personally tested this on my device, or explained why that is not possible

## Final pass
   - [x] Code is as readable as possible.
   - [x] I have reviewed this PR myself, ensuring it meets each checklist item

---
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/803)

### CODE REVIEW

**Review by jkasten2 — APPROVED** [review]
Just a noted on a comment, otherwise it looks good.

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/803#-:-N7vxsOu-260j07Ql00t:b-eqb6hh)* status: all files reviewed, 1 unresolved discussion (waiting on @emawby and @nan-li)

___
*[`www/index.ts` line 322 at r2](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/803#-N7vwrMrAzUKo8jIolJ4:-N7vwrMs9FoFV0s_S6iP:by29no4) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/fcb3a8eff5071cc3331b01ceab0151d0e7f7ebd0/www/index.ts#L322)):*
> ```XML
>     /**
>      * Prompts the user for push notifications permission in iOS and Android 13+.
>      * In lower Android versions, it will return false, since notification permission is by default given.
> ```

On Android 12 and older it should be returning the current permission. Or if fallbackToSetting is set and permission is currently `false` it should be waiting until they pick a prompt option.

**Review by nan-li — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/803)* status: all files reviewed, 1 unresolved discussion (waiting on @emawby and @jkasten2)

___
*[`www/index.ts` line 322 at r2](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/803#-N7vwrMrAzUKo8jIolJ4:-N7wd5ya5JLNL3rLih03:bgcd7x3) ([raw file](https://github.com/onesignal/onesignal-cordova-sdk/blob/fcb3a8eff5071cc3331b01ceab0151d0e7f7ebd0/www/index.ts#L322)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

On Android 12 and older it should be returning the current permission. Or if fallbackToSetting is set and permission is currently `false` it should be waiting until they pick a prompt option.
</blockquote></details>

You're right, this is a very misleading statement.

**Comment by jkasten2** [comment]
> There is some potentially undesirable behavior if a user taps outside the fallback to settings prompt to dismiss it. Since the SDK seems to be waiting on user interaction, the Android plugin's (and the user's) callback is not triggered until some definitive response is taken. Then they are all triggered. Included a short video to demonstrate.

ah nice find, I didn't think to test tapping outside of the dialog. The OneSignal-Android-SDK didn't account for that so this is a minor bug there. We can ship this PR without the fix and can follow up later on this edge case.

**Review by jkasten2 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-cordova-sdk/803)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @emawby)

**Pull request merged**
